# Generated by Django 4.1.2 on 2022-10-20 14:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dboard', '0002_remove_user_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_name', models.CharField(max_length=150, verbose_name='Название заявки')),
                ('disc', models.TextField(max_length=300, verbose_name='Описание')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания заявки')),
                ('status', models.CharField(blank=True, choices=[('2D', '2D-design'), ('3D', '3D-design'), ('Web', 'Web-design'), ('Mobile', 'Mobile-design')], default='Другое', help_text='Категория заказа', max_length=6)),
            ],
        ),
    ]
