# Generated by Django 4.1.2 on 2022-10-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dboard', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='category',
            field=models.CharField(blank=True, choices=[('2D', '2D-design'), ('3D', '3D-design'), ('Web', 'Web-design'), ('Mobile', 'Mobile-design')], default='Другое', help_text='Категория заказа', max_length=6, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('Новый', 'Заказ только поступил'), ('В работе', 'Заказ находится в разработке'), ('Выполнен', 'Заказ выполнен')], default='Другое', help_text='Категория заказа', max_length=8, verbose_name='Статус'),
        ),
    ]
