# Generated by Django 4.1.2 on 2022-10-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dboard', '0004_order_category_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('Новый', 'Новый'), ('В работе', 'В работе'), ('Выполнен', 'Выполнен')], default='Другое', help_text='Категория заказа', max_length=8, verbose_name='Статус'),
        ),
    ]
