# Generated by Django 4.1.2 on 2022-10-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dboard', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_img',
            field=models.ImageField(null=True, upload_to=None, verbose_name='Изображение'),
        ),
    ]
