# Generated by Django 4.1.2 on 2022-10-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dboard', '0007_alter_order_order_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_img',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Изображение'),
        ),
    ]
