# Generated by Django 4.1.2 on 2022-10-21 03:09

import dboard.utilities
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dboard', '0008_alter_order_order_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_img',
            field=models.ImageField(blank=True, upload_to=dboard.utilities.get_timestamp_path, verbose_name='Изображение'),
        ),
        migrations.CreateModel(
            name='AdditionalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_img', models.ImageField(upload_to=dboard.utilities.get_timestamp_path, verbose_name='Изображение')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dboard.order', verbose_name='Объявление')),
            ],
            options={
                'verbose_name': 'Дополнительная иллюстрация',
                'verbose_name_plural': 'Дополнительные иллюстрации',
            },
        ),
    ]
