# Generated by Django 4.1.2 on 2022-10-21 16:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dboard', '0011_alter_order_orderer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('Новый', 'Новый'), ('В работе', 'В работе'), ('Выполнен', 'Выполнен')], default='Новый', help_text='Категория заказа', max_length=8, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fio',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Имя пользователя содержит только кириллицу', regex='^[А-Яа-я -]*$')], verbose_name='ФИО'),
        ),
    ]
