# Generated by Django 4.1.2 on 2022-10-21 16:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dboard', '0012_alter_order_status_alter_user_fio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fio',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Поле ФИО содержит только кириллицу', regex='^[А-Яа-я -]*$')], verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Имя пользователя содержит только латиницу', regex='^[A-Za-z -]*$')], verbose_name='ФИО'),
        ),
    ]
