# Generated by Django 4.1.2 on 2022-10-21 16:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dboard', '0013_alter_user_fio_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Имя пользователя содержит только латиницу', regex='^[A-Za-z -]*$')], verbose_name='Логин'),
        ),
    ]
